# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon.fromTheme("my_ico")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(-10, 0, 1031, 770))
        self.tabs.setMinimumSize(QtCore.QSize(1000, 770))
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("\n"
"QTabBar::tab {\n"
"background: rgba(131, 131, 131, 15);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"margin-left: 15px;\n"
"padding: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"backgroud: rgb(60, 74, 202);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"backgroud: rgb(60, 74, 202, 0.15);\n"
"border-radius: 15px;\n"
"}")
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setTabBarAutoHide(True)
        self.tabs.setObjectName("tabs")
        self.taskTab = QtWidgets.QWidget()
        self.taskTab.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgba(131, 131, 131, 15);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";")
        self.taskTab.setObjectName("taskTab")
        self.lonelyTask = QtWidgets.QPlainTextEdit(self.taskTab)
        self.lonelyTask.setGeometry(QtCore.QRect(57, 138, 671, 461))
        self.lonelyTask.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Courier New\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.lonelyTask.setReadOnly(True)
        self.lonelyTask.setObjectName("lonelyTask")
        self.answerAlone = QtWidgets.QLineEdit(self.taskTab)
        self.answerAlone.setGeometry(QtCore.QRect(164, 628, 561, 21))
        self.answerAlone.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
        self.answerAlone.setText("")
        self.answerAlone.setObjectName("answerAlone")
        self.label_3 = QtWidgets.QLabel(self.taskTab)
        self.label_3.setGeometry(QtCore.QRect(60, 628, 91, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.answer1 = QtWidgets.QPushButton(self.taskTab)
        self.answer1.setGeometry(QtCore.QRect(164, 668, 191, 31))
        self.answer1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.answer1.setObjectName("answer1")
        self.showSol1 = QtWidgets.QPushButton(self.taskTab)
        self.showSol1.setGeometry(QtCore.QRect(540, 668, 181, 31))
        self.showSol1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.showSol1.setObjectName("showSol1")
        self.next1 = QtWidgets.QPushButton(self.taskTab)
        self.next1.setGeometry(QtCore.QRect(734, 350, 31, 31))
        self.next1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.next1.setObjectName("next1")
        self.prev1 = QtWidgets.QPushButton(self.taskTab)
        self.prev1.setGeometry(QtCore.QRect(20, 348, 31, 31))
        self.prev1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.prev1.setObjectName("prev1")
        self.label_5 = QtWidgets.QLabel(self.taskTab)
        self.label_5.setGeometry(QtCore.QRect(760, 140, 211, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.answerTable1 = QtWidgets.QTableWidget(self.taskTab)
        self.answerTable1.setGeometry(QtCore.QRect(780, 168, 211, 431))
        self.answerTable1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.answerTable1.setObjectName("answerTable1")
        self.answerTable1.setColumnCount(2)
        self.answerTable1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.answerTable1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.answerTable1.setHorizontalHeaderItem(1, item)
        self.frame = QtWidgets.QFrame(self.taskTab)
        self.frame.setGeometry(QtCore.QRect(20, 10, 971, 121))
        self.frame.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"border-width: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.saveFile1 = QtWidgets.QPushButton(self.frame)
        self.saveFile1.setGeometry(QtCore.QRect(700, 78, 265, 31))
        self.saveFile1.setMinimumSize(QtCore.QSize(0, 31))
        self.saveFile1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.saveFile1.setObjectName("saveFile1")
        self.chooseLink1 = QtWidgets.QComboBox(self.frame)
        self.chooseLink1.setGeometry(QtCore.QRect(700, 40, 265, 31))
        self.chooseLink1.setMinimumSize(QtCore.QSize(0, 31))
        self.chooseLink1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.chooseLink1.setFrame(False)
        self.chooseLink1.setObjectName("chooseLink1")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(700, 6, 265, 30))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.showTask1 = QtWidgets.QPushButton(self.frame)
        self.showTask1.setGeometry(QtCore.QRect(370, 78, 265, 31))
        self.showTask1.setMinimumSize(QtCore.QSize(0, 31))
        self.showTask1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.showTask1.setObjectName("showTask1")
        self.taskBox = QtWidgets.QComboBox(self.frame)
        self.taskBox.setGeometry(QtCore.QRect(370, 40, 265, 31))
        self.taskBox.setMinimumSize(QtCore.QSize(0, 31))
        self.taskBox.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.taskBox.setCurrentText("")
        self.taskBox.setFrame(False)
        self.taskBox.setObjectName("taskBox")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(370, 4, 265, 30))
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.allow1 = QtWidgets.QPushButton(self.frame)
        self.allow1.setGeometry(QtCore.QRect(40, 78, 265, 31))
        self.allow1.setMinimumSize(QtCore.QSize(0, 31))
        self.allow1.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.allow1.setObjectName("allow1")
        self.typeBox = QtWidgets.QComboBox(self.frame)
        self.typeBox.setGeometry(QtCore.QRect(40, 40, 265, 31))
        self.typeBox.setMinimumSize(QtCore.QSize(0, 31))
        self.typeBox.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.typeBox.setCurrentText("")
        self.typeBox.setFrame(False)
        self.typeBox.setObjectName("typeBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 4, 265, 30))
        self.label.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.taskTab)
        self.label_11.setGeometry(QtCore.QRect(-30, -20, 1031, 800))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("ui-design/background.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.lonelyTask.raise_()
        self.answerAlone.raise_()
        self.label_3.raise_()
        self.answer1.raise_()
        self.showSol1.raise_()
        self.next1.raise_()
        self.prev1.raise_()
        self.label_5.raise_()
        self.answerTable1.raise_()
        self.frame.raise_()
        self.tabs.addTab(self.taskTab, "")
        self.varTab = QtWidgets.QWidget()
        self.varTab.setObjectName("varTab")
        self.prev2 = QtWidgets.QPushButton(self.varTab)
        self.prev2.setGeometry(QtCore.QRect(20, 350, 31, 31))
        self.prev2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.prev2.setObjectName("prev2")
        self.answerTable2 = QtWidgets.QTableWidget(self.varTab)
        self.answerTable2.setGeometry(QtCore.QRect(780, 170, 211, 431))
        self.answerTable2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.answerTable2.setObjectName("answerTable2")
        self.answerTable2.setColumnCount(2)
        self.answerTable2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.answerTable2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.answerTable2.setHorizontalHeaderItem(1, item)
        self.answerVariant = QtWidgets.QLineEdit(self.varTab)
        self.answerVariant.setGeometry(QtCore.QRect(160, 630, 565, 21))
        self.answerVariant.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.answerVariant.setText("")
        self.answerVariant.setObjectName("answerVariant")
        self.variantTask = QtWidgets.QPlainTextEdit(self.varTab)
        self.variantTask.setGeometry(QtCore.QRect(57, 140, 671, 461))
        self.variantTask.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Courier New\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.variantTask.setReadOnly(True)
        self.variantTask.setObjectName("variantTask")
        self.next2 = QtWidgets.QPushButton(self.varTab)
        self.next2.setGeometry(QtCore.QRect(734, 352, 31, 31))
        self.next2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.next2.setObjectName("next2")
        self.label_6 = QtWidgets.QLabel(self.varTab)
        self.label_6.setGeometry(QtCore.QRect(60, 630, 91, 20))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_6.setObjectName("label_6")
        self.saveAnswer = QtWidgets.QPushButton(self.varTab)
        self.saveAnswer.setGeometry(QtCore.QRect(160, 670, 191, 31))
        self.saveAnswer.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.saveAnswer.setObjectName("saveAnswer")
        self.label_7 = QtWidgets.QLabel(self.varTab)
        self.label_7.setGeometry(QtCore.QRect(780, 140, 211, 20))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.createVar = QtWidgets.QPushButton(self.varTab)
        self.createVar.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.createVar.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.createVar.setObjectName("createVar")
        self.varBox = QtWidgets.QComboBox(self.varTab)
        self.varBox.setGeometry(QtCore.QRect(340, 50, 265, 31))
        self.varBox.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.varBox.setObjectName("varBox")
        self.label_8 = QtWidgets.QLabel(self.varTab)
        self.label_8.setGeometry(QtCore.QRect(340, 20, 265, 16))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.showRes = QtWidgets.QPushButton(self.varTab)
        self.showRes.setGeometry(QtCore.QRect(500, 670, 225, 31))
        self.showRes.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.showRes.setObjectName("showRes")
        self.saveFile2 = QtWidgets.QPushButton(self.varTab)
        self.saveFile2.setGeometry(QtCore.QRect(719, 90, 261, 31))
        self.saveFile2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.saveFile2.setObjectName("saveFile2")
        self.label_9 = QtWidgets.QLabel(self.varTab)
        self.label_9.setGeometry(QtCore.QRect(720, 20, 261, 20))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(60, 74, 202);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.chooseLink2 = QtWidgets.QComboBox(self.varTab)
        self.chooseLink2.setGeometry(QtCore.QRect(719, 50, 265, 31))
        self.chooseLink2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.chooseLink2.setFrame(True)
        self.chooseLink2.setObjectName("chooseLink2")
        self.allow2 = QtWidgets.QPushButton(self.varTab)
        self.allow2.setGeometry(QtCore.QRect(340, 90, 265, 31))
        self.allow2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(60, 74, 202);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 8pt \"Franklin Gothic Medium\";\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.allow2.setObjectName("allow2")
        self.label_12 = QtWidgets.QLabel(self.varTab)
        self.label_12.setGeometry(QtCore.QRect(-10, -10, 1021, 800))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("ui-design/background.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_12.raise_()
        self.prev2.raise_()
        self.answerTable2.raise_()
        self.answerVariant.raise_()
        self.variantTask.raise_()
        self.next2.raise_()
        self.label_6.raise_()
        self.saveAnswer.raise_()
        self.label_7.raise_()
        self.createVar.raise_()
        self.varBox.raise_()
        self.label_8.raise_()
        self.showRes.raise_()
        self.saveFile2.raise_()
        self.label_9.raise_()
        self.chooseLink2.raise_()
        self.allow2.raise_()
        self.tabs.addTab(self.varTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тренажер ЕГЭ"))
        self.label_3.setText(_translate("MainWindow", "Введите ответ:"))
        self.answer1.setText(_translate("MainWindow", "Ответить"))
        self.showSol1.setText(_translate("MainWindow", "Показать решение"))
        self.next1.setText(_translate("MainWindow", "->"))
        self.prev1.setText(_translate("MainWindow", "<-"))
        self.label_5.setText(_translate("MainWindow", "Введите ответ:"))
        item = self.answerTable1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.answerTable1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        self.saveFile1.setText(_translate("MainWindow", "Скачать"))
        self.label_4.setText(_translate("MainWindow", "Выберите файл для скачивания"))
        self.showTask1.setText(_translate("MainWindow", "Показать задание"))
        self.label_2.setText(_translate("MainWindow", "Выберите задание"))
        self.allow1.setText(_translate("MainWindow", "Применить"))
        self.label.setText(_translate("MainWindow", "Выберите тип задания"))
        self.tabs.setTabText(self.tabs.indexOf(self.taskTab), _translate("MainWindow", "Решать задачи"))
        self.prev2.setText(_translate("MainWindow", "<-"))
        item = self.answerTable2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.answerTable2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        self.next2.setText(_translate("MainWindow", "->"))
        self.label_6.setText(_translate("MainWindow", "Введите ответ:"))
        self.saveAnswer.setText(_translate("MainWindow", "Сохранить ответ на задание"))
        self.label_7.setText(_translate("MainWindow", "Введите ответ:"))
        self.createVar.setText(_translate("MainWindow", "Составить вариант"))
        self.label_8.setText(_translate("MainWindow", "Выбрать номер задания"))
        self.showRes.setText(_translate("MainWindow", "Завершить работу и узнать результат"))
        self.saveFile2.setText(_translate("MainWindow", "Скачать"))
        self.label_9.setText(_translate("MainWindow", "Выберите файл для скачивания"))
        self.allow2.setText(_translate("MainWindow", "Применить"))
        self.tabs.setTabText(self.tabs.indexOf(self.varTab), _translate("MainWindow", "Решать вариант"))
